# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Code\Bytetrack_Server\resource\ui\server.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1554, 926)
        self.videoLabel = PixmapLabel(Form)
        self.videoLabel.setGeometry(QtCore.QRect(10, 10, 1191, 711))
        self.videoLabel.setScaledContents(True)
        self.videoLabel.setObjectName("videoLabel")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(1240, 70, 271, 371))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ComboBox = ComboBox(self.frame)
        self.ComboBox.setGeometry(QtCore.QRect(30, 20, 201, 41))
        self.ComboBox.setObjectName("ComboBox")
        self.PushButton = PrimaryPushButton(self.frame)
        self.PushButton.setGeometry(QtCore.QRect(30, 90, 201, 31))
        self.PushButton.setStyleSheet("")
        self.PushButton.setObjectName("PushButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(40, 170, 181, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 91))
        self.label.setObjectName("label")
        self.ComboBox_2 = ComboBox(Form)
        self.ComboBox_2.setGeometry(QtCore.QRect(60, 790, 221, 41))
        self.ComboBox_2.setObjectName("ComboBox_2")
        self.imageView = QtWidgets.QGraphicsView(Form)
        self.imageView.setGeometry(QtCore.QRect(5, 11, 1251, 771))
        self.imageView.setObjectName("imageView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PushButton.setText(_translate("Form", "选择"))
        self.label.setText(_translate("Form", "TextLabel"))
from qfluentwidgets import ComboBox, PixmapLabel, PrimaryPushButton
